name: deploy
on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'release/**'
      - 'feature/build-workflow'

jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [windows-latest, ubuntu-20.04, macOS-latest]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[pyinstaller]
      - name: Generate Antares Launcher application
        run: |
          pyinstaller -F antareslauncher/advanced_launch.py -n Antares_Launcher
        env:
          PYTHONPATH: .
      - name: Archive Windows Application
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Antares_Launcher
          path: dist/Antares_Launcher.exe
      - name: Archive POSIX Application
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: Antares_Launcher
          path: dist/Antares_Launcher
