name: deploy
on:
  push:
    branches:
      - 'pbq/build/binary'


jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate Windows binary
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller -F antareslauncher/advanced_launch.py -n Antares_Launcher
        env:
          PYTHONPATH: .
      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: Antares_Launcher
          path: dist/Antares_Launcher.exe
